// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebCrawlerApi.Data;

#nullable disable

namespace WebCrawlerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410064655_20260410_InitialSchema")]
    partial class _20260410_InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebCrawlerApi.Data.Entities.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<JsonDocument>("Condition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("condition");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("MessageTpl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_tpl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_alert_rules");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_alert_rules_source_id");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("WebCrawlerApi.Data.Entities.CrawlJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_crawl_jobs");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_crawl_jobs_source_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_crawl_jobs_status");

                    b.HasIndex("Url", "ContentHash")
                        .HasDatabaseName("ix_crawl_jobs_url_content_hash");

                    b.ToTable("crawl_jobs", (string)null);
                });

            modelBuilder.Entity("WebCrawlerApi.Data.Entities.DataEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CrawledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("crawled_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EntryKey")
                        .HasColumnType("text")
                        .HasColumnName("entry_key");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_data_entries");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_data_entries_category");

                    b.HasIndex("CrawledAt")
                        .IsDescending()
                        .HasDatabaseName("ix_data_entries_crawled_at");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_data_entries_job_id");

                    b.HasIndex("Payload")
                        .HasDatabaseName("ix_data_entries_payload");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Payload"), "gin");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_data_entries_source_id");

                    b.HasIndex("SourceId", "EntryKey")
                        .IsUnique()
                        .HasDatabaseName("ix_data_entries_source_id_entry_key");

                    b.ToTable("data_entries", (string)null);
                });

            modelBuilder.Entity("WebCrawlerApi.Data.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AlertRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_rule_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<Guid?>("DataEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_entry_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("sent")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_notification_logs");

                    b.HasIndex("AlertRuleId")
                        .HasDatabaseName("ix_notification_logs_alert_rule_id");

                    b.HasIndex("DataEntryId")
                        .HasDatabaseName("ix_notification_logs_data_entry_id");

                    b.HasIndex("SentAt")
                        .IsDescending()
                        .HasDatabaseName("ix_notification_logs_sent_at");

                    b.ToTable("notification_logs", (string)null);
                });

            modelBuilder.Entity("WebCrawlerApi.Data.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int>("CrawlInterval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3600)
                        .HasColumnName("crawl_interval");

                    b.Property<string>("CrawlerType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("cheerio")
                        .HasColumnName("crawler_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastCrawledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_crawled_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ParserKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parser_key");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_sources");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_sources_category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_sources_is_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_sources_name");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("WebCrawlerApi.Data.Entities.AlertRule", b =>
                {
                    b.HasOne("WebCrawlerApi.Data.Entities.Source", "Source")
                        .WithMany("AlertRules")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alert_rules_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("WebCrawlerApi.Data.Entities.CrawlJob", b =>
                {
                    b.HasOne("WebCrawlerApi.Data.Entities.Source", "Source")
                        .WithMany("CrawlJobs")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_crawl_jobs_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("WebCrawlerApi.Data.Entities.DataEntry", b =>
                {
                    b.HasOne("WebCrawlerApi.Data.Entities.CrawlJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_data_entries_crawl_jobs_job_id");

                    b.HasOne("WebCrawlerApi.Data.Entities.Source", "Source")
                        .WithMany("DataEntries")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_data_entries_sources_source_id");

                    b.Navigation("Job");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("WebCrawlerApi.Data.Entities.NotificationLog", b =>
                {
                    b.HasOne("WebCrawlerApi.Data.Entities.AlertRule", "AlertRule")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_logs_alert_rules_alert_rule_id");

                    b.HasOne("WebCrawlerApi.Data.Entities.DataEntry", "DataEntry")
                        .WithMany()
                        .HasForeignKey("DataEntryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notification_logs_data_entries_data_entry_id");

                    b.Navigation("AlertRule");

                    b.Navigation("DataEntry");
                });

            modelBuilder.Entity("WebCrawlerApi.Data.Entities.AlertRule", b =>
                {
                    b.Navigation("NotificationLogs");
                });

            modelBuilder.Entity("WebCrawlerApi.Data.Entities.Source", b =>
                {
                    b.Navigation("AlertRules");

                    b.Navigation("CrawlJobs");

                    b.Navigation("DataEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
