apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: webcrawler-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      prometheusVersion: "3.11.3"
      prometheusType: Prometheus
    editable: true
